name: Create Board Firmware

on:
  schedule:
    - cron: '10 17 * * *' # build fresh every 5:10 PM
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-firmware:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build firmware
      uses: ./ext/rusefi/.github/workflows/custom-board-build
      with:
        artifacts: bin srec hex list map elf bundle
        uploads: ""
        push: "false"

    - name: Upload firmware artifacts
      uses: actions/upload-artifact@v4
      with:
        name: rusefi-build
        path: |
          firmware/build/**
