name: Create Board Firmware

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: rusefi/rusefi/.github/workflows/custom-board-build.yaml@master
    secrets: inherit
    permissions:
      contents: write
    with:
      shortBoardName: core8
      iniFileName: rusefi_core8.ini
